# Конфігурація для збору метрик у Victoriametrics
scrape_configs:
  # Конфігурація для збору метрик із Flask-агента
  - job_name: 'monitoring_agent'  # Ім'я задачі для ідентифікації джерела метрик
    scrape_interval: 3s  # Інтервал збору метрик (кожні 3 секунди)
    static_configs:
      - targets: ['192.168.0.131:8000']  # Список цільових адрес для скрейпінгу (Flask-агент)